//@error-in-other-file: aborting due to previous error

fn main() {
    2 + +2;
}
