error: this `RefCell` reference is held across an `await` point
  --> tests/ui/await_holding_refcell_ref.rs:6:9
   |
LL |     let b = x.borrow();
   |         ^
   |
   = help: ensure the reference is dropped before calling `await`
note: these are all the `await` points this reference is held through
  --> tests/ui/await_holding_refcell_ref.rs:8:11
   |
LL |     baz().await
   |           ^^^^^
   = note: `-D clippy::await-holding-refcell-ref` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::await_holding_refcell_ref)]`

error: this `RefCell` reference is held across an `await` point
  --> tests/ui/await_holding_refcell_ref.rs:12:9
   |
LL |     let b = x.borrow_mut();
   |         ^
   |
   = help: ensure the reference is dropped before calling `await`
note: these are all the `await` points this reference is held through
  --> tests/ui/await_holding_refcell_ref.rs:14:11
   |
LL |     baz().await
   |           ^^^^^

error: this `RefCell` reference is held across an `await` point
  --> tests/ui/await_holding_refcell_ref.rs:34:9
   |
LL |     let b = x.borrow_mut();
   |         ^
   |
   = help: ensure the reference is dropped before calling `await`
note: these are all the `await` points this reference is held through
  --> tests/ui/await_holding_refcell_ref.rs:37:24
   |
LL |     let second = baz().await;
   |                        ^^^^^
LL |
LL |     let third = baz().await;
   |                       ^^^^^

error: this `RefCell` reference is passed in through an argument or captured by the closure body
  --> tests/ui/await_holding_refcell_ref.rs:44:22
   |
LL | async fn equally_bad(x: Ref<'_, u32>) {
   |                      ^
   |
   = help: ensure the `RefCell` reference is not passed as an argument, captured or kept before calling `await`

error: this `RefCell` reference is held across an `await` point
  --> tests/ui/await_holding_refcell_ref.rs:51:9
   |
LL |     let b = x.borrow_mut();
   |         ^
   |
   = help: ensure the reference is dropped before calling `await`
note: these are all the `await` points this reference is held through
  --> tests/ui/await_holding_refcell_ref.rs:54:24
   |
LL |     let second = baz().await;
   |                        ^^^^^

error: this `RefCell` reference is held across an `await` point
  --> tests/ui/await_holding_refcell_ref.rs:67:13
   |
LL |         let b = x.borrow_mut();
   |             ^
   |
   = help: ensure the reference is dropped before calling `await`
note: these are all the `await` points this reference is held through
  --> tests/ui/await_holding_refcell_ref.rs:69:15
   |
LL |         baz().await
   |               ^^^^^

error: this `RefCell` reference is held across an `await` point
  --> tests/ui/await_holding_refcell_ref.rs:80:13
   |
LL |         let b = x.borrow_mut();
   |             ^
   |
   = help: ensure the reference is dropped before calling `await`
note: these are all the `await` points this reference is held through
  --> tests/ui/await_holding_refcell_ref.rs:82:15
   |
LL |         baz().await
   |               ^^^^^

error: aborting due to 7 previous errors

