error: returning an `Err(_)` with the `?` operator
  --> tests/ui/try_err.rs:22:9
   |
LL |         Err(err)?;
   |         ^^^^^^^^^
   |
note: the lint level is defined here
  --> tests/ui/try_err.rs:3:9
   |
LL | #![deny(clippy::try_err)]
   |         ^^^^^^^^^^^^^^^
help: try
   |
LL |         return Err(err);
   |         ~~~~~~~~~~~~~~~

error: returning an `Err(_)` with the `?` operator
  --> tests/ui/try_err.rs:32:9
   |
LL |         Err(err)?;
   |         ^^^^^^^^^
   |
help: try
   |
LL |         return Err(err.into());
   |         ~~~~~~~~~~~~~~~~~~~~~~

error: returning an `Err(_)` with the `?` operator
  --> tests/ui/try_err.rs:52:17
   |
LL |                 Err(err)?;
   |                 ^^^^^^^^^
   |
help: try
   |
LL |                 return Err(err);
   |                 ~~~~~~~~~~~~~~~

error: returning an `Err(_)` with the `?` operator
  --> tests/ui/try_err.rs:71:17
   |
LL |                 Err(err)?;
   |                 ^^^^^^^^^
   |
help: try
   |
LL |                 return Err(err.into());
   |                 ~~~~~~~~~~~~~~~~~~~~~~

error: returning an `Err(_)` with the `?` operator
  --> tests/ui/try_err.rs:91:23
   |
LL |             Err(_) => Err(1)?,
   |                       ^^^^^^^
   |
   = note: this error originates in the macro `__inline_mac_fn_calling_macro` (in Nightly builds, run with -Z macro-backtrace for more info)
help: try
   |
LL |             Err(_) => return Err(1),
   |                       ~~~~~~~~~~~~~

error: returning an `Err(_)` with the `?` operator
  --> tests/ui/try_err.rs:98:23
   |
LL |             Err(_) => Err(inline!(1))?,
   |                       ^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `__inline_mac_fn_calling_macro` (in Nightly builds, run with -Z macro-backtrace for more info)
help: try
   |
LL |             Err(_) => return Err(inline!(1)),
   |                       ~~~~~~~~~~~~~~~~~~~~~~

error: returning an `Err(_)` with the `?` operator
  --> tests/ui/try_err.rs:125:9
   |
LL |         Err(inline!(inline!(String::from("aasdfasdfasdfa"))))?;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: try
   |
LL |         return Err(inline!(inline!(String::from("aasdfasdfasdfa"))));
   |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error: returning an `Err(_)` with the `?` operator
  --> tests/ui/try_err.rs:132:9
   |
LL |         Err(io::ErrorKind::WriteZero)?
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: try
   |
LL |         return Poll::Ready(Err(io::ErrorKind::WriteZero.into()))
   |

error: returning an `Err(_)` with the `?` operator
  --> tests/ui/try_err.rs:134:9
   |
LL |         Err(io::Error::new(io::ErrorKind::InvalidInput, "error"))?
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: try
   |
LL |         return Poll::Ready(Err(io::Error::new(io::ErrorKind::InvalidInput, "error")))
   |

error: returning an `Err(_)` with the `?` operator
  --> tests/ui/try_err.rs:142:9
   |
LL |         Err(io::ErrorKind::NotFound)?
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: try
   |
LL |         return Poll::Ready(Some(Err(io::ErrorKind::NotFound.into())))
   |

error: returning an `Err(_)` with the `?` operator
  --> tests/ui/try_err.rs:151:16
   |
LL |         return Err(42)?;
   |                ^^^^^^^^
   |
help: try
   |
LL |         return Err(42);
   |                ~~~~~~~

error: aborting due to 11 previous errors

